In [1]:
import gym
env = gym.make('CartPole-v1')

In [2]:
print (env.observation_space) 

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)


In [3]:
print(env.reset())

(array([ 0.00703839, -0.00943191,  0.00738025,  0.03460035], dtype=float32), {})


In [4]:
print (env.observation_space.high)


[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]


In [5]:
print (env.observation_space.low)

[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [6]:
env.action_space

Discrete(2)

In [7]:
pos_char, vit_char, ang_per, vit_per, prob = env.step(env.action_space.sample())
print(pos_char, vit_char, ang_per, vit_per)

[ 0.00684975 -0.20465891  0.00807225  0.32960266] 1.0 False False


c:\Python311\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [8]:
num_episodes = 100
num_timesteps = 50 #(nombre de pas de temps dans un épisode) 

def deroulement(num_timesteps:int, num_episodes:int=0):
    env.reset()
    i = 0
    j = 0
    random_action = env.action_space.sample()
    new_state, reward, done, info, prob = env.step(random_action) 
    for i in range(num_episodes):
        env.reset()
        score = 0
        j = 0        
        for j in range(num_timesteps):
            random_action = env.action_space.sample()
            new_state, reward, done, info, prob = env.step(random_action)            
            if reward == 1:
                score += reward            
            j += 1
        i += 1
        if i%10 == 0:
            print(f"episode {i}: {score}")
        

deroulement(num_timesteps, num_episodes)

episode 10: 27.0
episode 20: 12.0
episode 30: 22.0
episode 40: 21.0
episode 50: 14.0
episode 60: 16.0
episode 70: 18.0
episode 80: 50.0
episode 90: 20.0
episode 100: 21.0


c:\Python311\Lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(
